workspace = { members = [ "game_server", "matchmaking_server" ] }
[package]
name = "web-4d-shooter"
version = "0.4.2"
edition = "2021"
# author = "maffi44"
# wasm-opt = false

[dependencies]

matchmaking_server = { path = "./matchmaking_server" }
game_server = { path = "./game_server" }
env_logger = "*"
winit = {version = "*", features = ["rwh_05"]}
windows-sys = {version = "*", features = ["Win32", "Win32_Media"]}
# wgpu = { version = "*", default-features = false, features = ["webgl", "glsl", "spirv", "wgsl", "naga"]}
wgpu = { version = "*" }
bytemuck = { version = "*", features = [ "derive" ] }
pollster = "*"
tokio = "*"
tokio-tungstenite = "*"
web-time = "0.2.4"
glam = "*"
rand = "*"
blink-alloc = "*"
fyrox-sound = "*"
fyrox-resource = "*"
fyrox-core = "*"
image = "*"
log = "*"
serde_json = "*"
alkahest = { version = "*", features = [ "derive" ] }
bincode = "*"
console_error_panic_hook = "*"
console_log = "*"
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
getrandom = { version = "*", features = [ "js" ] }
web-sys = { version = "*", features = [
    "Document",
    "Window",
    "Element",
    "console",
    "Performance",
    "Response"
]}
matchbox_socket = { version = "*", features = [] }
rustc-hash = "1.1.0"

[lib]
name="game_client_main_web"
path = "src/game_client_main_web.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name="game-client"
path="src/game_client_fast_main.rs"

[[bin]]
name="game-client-for-map-editing"
path="src/game_client_main.rs"

[[bin]]
name="game-client-2d-3d-example"
path="src/game_client_for_2d_3d_example_main.rs"

[[bin]]
name="game-client-2d-3d-example-fast"
path="src/game_client_for_2d_3d_example_fast_main.rs"

[[bin]]
name="game-client-observer"
path="src/game_client_observer_main.rs"

[[bin]]
name="headless-game-client-for-net-test"
path="src/headless_game_client_main_for_net_test.rs"

[[bin]]
name="raymarch_shader_generator"
path="src/raymarch_shader_generator.rs"

