[package]
name = "web-4d-shooter"
author = "maffi44"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# matchbox_socket = "*"
# webrtc = "*"
# env_logger = "*"
winit = {version = "0.29", features = ["rwh_05"]}
wgpu = { version = "*", default-features = false, features = ["webgl", "wgsl"]}
bytemuck = { version = "*", features = [ "derive" ] }
pollster = "*"
web-time = "0.2.4"
glam = "*"
#glm = "*"
log = "*"
serde_json = "*"
console_error_panic_hook = "*"
console_log = "*"
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
getrandom = { version = "*", features = [ "js" ] }
web-sys = { version = "*", features = [
    "Document",
    "Window",
    "Element",
    "console",
    "Performance",
    "Response"
]}

[lib]
crate-type = ["cdylib", "rlib"]


