workspace = { members = [ "game_server", "matchmaking_server" ] }
[package]
name = "web-4d-shooter"
author = "maffi44"
version = "0.1.3"
edition = "2021"
wasm-opt = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# matchbox_socket = "*"
# webrtc = "*"
matchmaking_server = { path = "./matchmaking_server" }
game_server = { path = "./game_server" }
env_logger = "*"
winit = {version = "0.29", features = ["rwh_05"]}
wgpu = { version = "*", default-features = false, features = ["webgl", "glsl", "spirv", "wgsl", "naga"]}
bytemuck = { version = "*", features = [ "derive" ] }
pollster = "*"
tokio = "*"
tokio-tungstenite = "*"
web-time = "0.2.4"
glam = "*"
rand = "*"

blink-alloc = "*"

fyrox-sound = "*"
fyrox-resource = "*"
fyrox-core = "*"

image = "*"

log = "*"
serde_json = "*"
alkahest = { version = "*", features = [ "derive" ] }
bincode = "*"
console_error_panic_hook = "*"
console_log = "*"
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
getrandom = { version = "*", features = [ "js" ] }
web-sys = { version = "*", features = [
    "Document",
    "Window",
    "Element",
    "console",
    "Performance",
    "Response"
]}
matchbox_socket = "*"
rustc-hash = "1.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name="game-client"
path="src/game_client_main.rs"

