name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Set up SSH access to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Install tomlq
      run: |
        pip install tomlq

    - name: Extract version from Cargo.toml
      id: cargo_version
      run: |
        version=$(tomlq -r '.package.version' Cargo.toml)
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: SSH into EC2 and deploy
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          set -e

          cd /opt/4dShooter/slice-4d-shooter

          git pull origin main

          # Build Rust binaries
          cargo build --release -p matchmaking_server
          cargo build --release -p game_server

          # Update matchmaking-server-config.json version
          jq '.current_game_version = "${{ env.VERSION }}"' /opt/4dShooter/matchmaking-server-config.json > /tmp/config.tmp
          sudo mv /tmp/config.tmp /opt/4dShooter/matchmaking-server-config.json

          # Define paths
          NEW_MATCHMAKING="./target/x86_64-unknown-linux-gnu/release/matchmaking_server"
          OLD_MATCHMAKING="/opt/4dShooter/matchmaking_server"

          NEW_GAME="./target/x86_64-unknown-linux-gnu/release/game_server"
          OLD_GAME="/opt/4dShooter/game_server"

          # Compare binaries
          RESTART_NEEDED=0

          if ! cmp -s "\$NEW_MATCHMAKING" "\$OLD_MATCHMAKING"; then
            echo "matchmaking_server has changed"
            RESTART_NEEDED=1
          fi

          if ! cmp -s "\$NEW_GAME" "\$OLD_GAME"; then
            echo "game_server has changed"
            RESTART_NEEDED=1
          fi

          if [ "\$RESTART_NEEDED" -eq 1 ]; then
            echo "Restarting matchmaking.service due to binary changes..."
            sudo systemctl stop matchmaking.service

            cp "\$NEW_MATCHMAKING" "\$OLD_MATCHMAKING"
            cp "\$NEW_GAME" "\$OLD_GAME"

            sudo systemctl start matchmaking.service
          else
            echo "No changes in binaries. Skipping restart."
          fi
        EOF

