name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH access to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Install tomlq
      run: |
        pip install tomlq

    - name: Extract version from Cargo.toml
      id: cargo_version
      run: |
        version=$(tomlq -r '.package.version' Cargo.toml)
        echo "VERSION=$version" >> $GITHUB_ENV

    - name: SSH into EC2 and deploy
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          set -e

          cd /opt/4dShooter/slice-4d-shooter

          git pull origin main

          # Build Rust binaries
          cargo build --release -p matchmaking_server
          cargo build --release -p game_server

          # Update matchmaking-server-config.json version
          jq '.current_game_version = "${{ env.VERSION }}"' /opt/4dShooter/matchmaking-server-config.json > /tmp/config.tmp
          sudo mv /tmp/config.tmp /opt/4dShooter/matchmaking-server-config.json

          # Stop the systemd service
          sudo systemctl stop matchmaking.service

          # Replace old binaries with new ones
          cp /opt/4dShooter/slice-4d-shooter/target/x86_64-unknown-linux-gnu/release/matchmaking_server /opt/4dShooter
          cp /opt/4dShooter/slice-4d-shooter/target/x86_64-unknown-linux-gnu/release/matchmaking_server /opt/4dShooter

          # Restart the systemd service
          sudo systemctl start matchmaking.service
        EOF
